
/*
Auto-generated by CVXPYgen on March 07, 2024 at 19:14:03.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_max_effort(1.00000000000000000000);
  cpg_update_thrust_mat(0, 1.00000000000000000000);
  cpg_update_moment(0, 0.34896654058232912110);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<4; i++) {
    printf("activation[%d] = %f\n", i, CPG_Result.prim->activation[i]);
  }

  // Print dual solution
  for(i=0; i<4; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<4; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<3; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }

  return 0;

}
