
/*
Auto-generated by CVXPYgen on March 01, 2024 at 10:36:37.
Content: Python binding with pybind11.
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <ctime>
#include "cpg_module.hpp"

extern "C" {
    #include "include/cpg_workspace.h"
    #include "include/cpg_solve.h"
}

namespace py = pybind11;

static int i;

CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp){

    // Pass changed user-defined parameter values to the solver
    if (CPG_Updated_cpp.max_velocity) {
        cpg_update_max_velocity(CPG_Params_cpp.max_velocity);
    }
    if (CPG_Updated_cpp.max_effort) {
        cpg_update_max_effort(CPG_Params_cpp.max_effort);
    }
    if (CPG_Updated_cpp.A) {
        for(i=0; i<36; i++) {
            cpg_update_A(i, CPG_Params_cpp.A[i]);
        }
    }
    if (CPG_Updated_cpp.B) {
        for(i=0; i<18; i++) {
            cpg_update_B(i, CPG_Params_cpp.B[i]);
        }
    }
    if (CPG_Updated_cpp.x_init) {
        for(i=0; i<6; i++) {
            cpg_update_x_init(i, CPG_Params_cpp.x_init[i]);
        }
    }
    if (CPG_Updated_cpp.x_target) {
        for(i=0; i<6; i++) {
            cpg_update_x_target(i, CPG_Params_cpp.x_target[i]);
        }
    }

    // Solve
    std::clock_t ASA_start = std::clock();
    cpg_solve();
    std::clock_t ASA_end = std::clock();

    // Arrange and return results
    CPG_Prim_cpp_t CPG_Prim_cpp {};
    for(i=0; i<30; i++) {
        CPG_Prim_cpp.U[i] = CPG_Prim.U[i];
    }
    for(i=0; i<66; i++) {
        CPG_Prim_cpp.X[i] = CPG_Prim.X[i];
    }
    CPG_Dual_cpp_t CPG_Dual_cpp {};
    for(i=0; i<33; i++) {
        CPG_Dual_cpp.d0[i] = CPG_Dual.d0[i];
    }
    for(i=0; i<30; i++) {
        CPG_Dual_cpp.d1[i] = CPG_Dual.d1[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d2[i] = CPG_Dual.d2[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d3[i] = CPG_Dual.d3[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d4[i] = CPG_Dual.d4[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d5[i] = CPG_Dual.d5[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d6[i] = CPG_Dual.d6[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d7[i] = CPG_Dual.d7[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d8[i] = CPG_Dual.d8[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d9[i] = CPG_Dual.d9[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d10[i] = CPG_Dual.d10[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d11[i] = CPG_Dual.d11[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d12[i] = CPG_Dual.d12[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d13[i] = CPG_Dual.d13[i];
    }
    CPG_Info_cpp_t CPG_Info_cpp {};
    CPG_Info_cpp.obj_val = CPG_Info.obj_val;
    CPG_Info_cpp.iter = CPG_Info.iter;
    CPG_Info_cpp.status = CPG_Info.status;
    CPG_Info_cpp.pri_res = CPG_Info.pri_res;
    CPG_Info_cpp.dua_res = CPG_Info.dua_res;
    CPG_Info_cpp.time = 1.0 * (ASA_end - ASA_start) / CLOCKS_PER_SEC;
    CPG_Result_cpp_t CPG_Result_cpp {};
    CPG_Result_cpp.prim = CPG_Prim_cpp;
    CPG_Result_cpp.dual = CPG_Dual_cpp;
    CPG_Result_cpp.info = CPG_Info_cpp;
    return CPG_Result_cpp;

}

PYBIND11_MODULE(cpg_module, m) {

    py::class_<CPG_Params_cpp_t>(m, "cpg_params")
            .def(py::init<>())
            .def_readwrite("max_velocity", &CPG_Params_cpp_t::max_velocity)
            .def_readwrite("max_effort", &CPG_Params_cpp_t::max_effort)
            .def_readwrite("A", &CPG_Params_cpp_t::A)
            .def_readwrite("B", &CPG_Params_cpp_t::B)
            .def_readwrite("x_init", &CPG_Params_cpp_t::x_init)
            .def_readwrite("x_target", &CPG_Params_cpp_t::x_target)
            ;

    py::class_<CPG_Updated_cpp_t>(m, "cpg_updated")
            .def(py::init<>())
            .def_readwrite("max_velocity", &CPG_Updated_cpp_t::max_velocity)
            .def_readwrite("max_effort", &CPG_Updated_cpp_t::max_effort)
            .def_readwrite("A", &CPG_Updated_cpp_t::A)
            .def_readwrite("B", &CPG_Updated_cpp_t::B)
            .def_readwrite("x_init", &CPG_Updated_cpp_t::x_init)
            .def_readwrite("x_target", &CPG_Updated_cpp_t::x_target)
            ;

    py::class_<CPG_Prim_cpp_t>(m, "cpg_prim")
            .def(py::init<>())
            .def_readwrite("U", &CPG_Prim_cpp_t::U)
            .def_readwrite("X", &CPG_Prim_cpp_t::X)
            ;

    py::class_<CPG_Dual_cpp_t>(m, "cpg_dual")
            .def(py::init<>())
            .def_readwrite("d0", &CPG_Dual_cpp_t::d0)
            .def_readwrite("d1", &CPG_Dual_cpp_t::d1)
            .def_readwrite("d2", &CPG_Dual_cpp_t::d2)
            .def_readwrite("d3", &CPG_Dual_cpp_t::d3)
            .def_readwrite("d4", &CPG_Dual_cpp_t::d4)
            .def_readwrite("d5", &CPG_Dual_cpp_t::d5)
            .def_readwrite("d6", &CPG_Dual_cpp_t::d6)
            .def_readwrite("d7", &CPG_Dual_cpp_t::d7)
            .def_readwrite("d8", &CPG_Dual_cpp_t::d8)
            .def_readwrite("d9", &CPG_Dual_cpp_t::d9)
            .def_readwrite("d10", &CPG_Dual_cpp_t::d10)
            .def_readwrite("d11", &CPG_Dual_cpp_t::d11)
            .def_readwrite("d12", &CPG_Dual_cpp_t::d12)
            .def_readwrite("d13", &CPG_Dual_cpp_t::d13)
            ;

    py::class_<CPG_Info_cpp_t>(m, "cpg_info")
            .def(py::init<>())
            .def_readwrite("obj_val", &CPG_Info_cpp_t::obj_val)
            .def_readwrite("iter", &CPG_Info_cpp_t::iter)
            .def_readwrite("status", &CPG_Info_cpp_t::status)
            .def_readwrite("pri_res", &CPG_Info_cpp_t::pri_res)
            .def_readwrite("dua_res", &CPG_Info_cpp_t::dua_res)
            .def_readwrite("time", &CPG_Info_cpp_t::time)
            ;

    py::class_<CPG_Result_cpp_t>(m, "cpg_result")
            .def(py::init<>())
            .def_readwrite("cpg_prim", &CPG_Result_cpp_t::prim)
            .def_readwrite("cpg_dual", &CPG_Result_cpp_t::dual)
            .def_readwrite("cpg_info", &CPG_Result_cpp_t::info)
            ;

    m.def("solve", &solve_cpp);

    m.def("set_solver_default_settings", &cpg_set_solver_default_settings);
    m.def("set_solver_normalize", &cpg_set_solver_normalize);
    m.def("set_solver_scale", &cpg_set_solver_scale);
    m.def("set_solver_adaptive_scale", &cpg_set_solver_adaptive_scale);
    m.def("set_solver_rho_x", &cpg_set_solver_rho_x);
    m.def("set_solver_max_iters", &cpg_set_solver_max_iters);
    m.def("set_solver_eps_abs", &cpg_set_solver_eps_abs);
    m.def("set_solver_eps_rel", &cpg_set_solver_eps_rel);
    m.def("set_solver_eps_infeas", &cpg_set_solver_eps_infeas);
    m.def("set_solver_alpha", &cpg_set_solver_alpha);
    m.def("set_solver_time_limit_secs", &cpg_set_solver_time_limit_secs);
    m.def("set_solver_verbose", &cpg_set_solver_verbose);
    m.def("set_solver_warm_start", &cpg_set_solver_warm_start);
    m.def("set_solver_acceleration_lookback", &cpg_set_solver_acceleration_lookback);
    m.def("set_solver_acceleration_interval", &cpg_set_solver_acceleration_interval);
    m.def("set_solver_write_data_filename", &cpg_set_solver_write_data_filename);
    m.def("set_solver_log_csv_filename", &cpg_set_solver_log_csv_filename);

}
